pub mod ui;
pub mod param_tabs;
pub mod result_tabs;
pub mod views;
pub mod collection;
pub mod request;
pub mod homepage;
mod creating_new_collection;
mod creating_new_request;
mod deleting_collection;
mod deleting_request;