# Base colors:
# Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray
# LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White
#
# Hex codes also work, e.g.  "#1a2b3c"

[ui]
font_color = "White"
# This can be null to preserve original terminal background
# app_background = "Black"

main_foreground_color = "White"
secondary_foreground_color = "DarkGray"

main_background_color = "DarkGray"
secondary_background_color = "#323232"

[others]
selection_highlight_color = "Yellow"
environment_variable_highlight_color = "Cyan"

[HTTP]
[HTTP.methods]
GET = "Green"
POST = "Yellow"
PUT = "LightBlue"
PATCH = "LightCyan"
DELETE = "LightRed"
OPTIONS = "Magenta"
HEAD = "Green"
TRACE = "Yellow"
CONNECT = "LightBlue"

[websocket]
[websocket.connection_status]
connected = "Green"
disconnected = "Red"

[websocket.messages]
server_foreground_color = "Blue"
server_background_color = "DarkGray"
you_background_color = "DarkGray"
details_color = "DarkGray"