# Base colors:
# Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray
# LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White
#
# Hex codes also work, e.g.  "#1a2b3c"

[ui]
font_color = "#606060"

# This can be null to preserve original terminal background
app_background = "#ede9da"

main_foreground_color = "#c8a1e0"
secondary_foreground_color = "#a0a0a0"

main_background_color = "#a0a0a0"
secondary_background_color = "#808080"

[others]
selection_highlight_color = "LightYellow"
environment_variable_highlight_color = "LightCyan"

[HTTP]
[HTTP.methods]
GET = "#acd668"
POST = "#f0d175"
PUT = "#7ac9f0"
PATCH = "#47c0c8"
DELETE = "#d18fa3"
OPTIONS = "#C8A1E0"
HEAD = "#CCE0AC"
TRACE = "#f0d175"
CONNECT = "#7ac9f0"

[websocket]
[websocket.connection_status]
connected = "#acd668"
disconnected = "#d18fa3"

[websocket.messages]
server_foreground_color = "#c8a1e0"
server_background_color = "#a0a0a0"
you_background_color = "#a0a0a0"
details_color = "Gray"